FROM pandoc/core:latest-ubuntu

# set secrets
ARG TELEGRAM_TOKEN
ENV TELEGRAM_TOKEN=$TELEGRAM_TOKEN

# install python and pip
RUN apt-get update -y
RUN apt-get install -y python3 \
    python3-pip

# install python packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# install texlive
sudo apt-get install  \
    texlive-xetex  \
    texlive-fonts-recommended  \
    texlive-plain-generic

# copy files
ARG FUNCTION_DIR="/function"
RUN mkdir -p ${FUNCTION_DIR}
COPY app/* ${FUNCTION_DIR}

# install aws lambda runtime
ARG LAMBDA_TASK_ROOT="/var/task"
RUN mkdir -p ${LAMBDA_TASK_ROOT}
RUN pip install \
        --target ${LAMBDA_TASK_ROOT} \
        awslambdaric

# set entrypoint and cmd
ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD [ "main.handler" ]