FROM pandoc/core:latest-ubuntu

# set secrets
ARG TELEGRAM_TOKEN
ENV TELEGRAM_TOKEN=${TELEGRAM_TOKEN}

# install python and pip
RUN apt-get update -y
RUN apt-get install -y python3 \
    python3-pip

# install texlive
RUN apt-get install -y \
    texlive-xetex  \
    texlive-fonts-recommended  \
    texlive-plain-generic

# install python dependencies
RUN pip install --upgrade pip
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
RUN rm /requirements.txt

# copy app files
ARG FUNCTION_DIR="/function/"
RUN mkdir -p ${FUNCTION_DIR}
COPY ./app/ ${FUNCTION_DIR}

# set entrypoint and cmd
WORKDIR ${FUNCTION_DIR}
ENTRYPOINT [ "/usr/bin/python3", "-m", "awslambdaric" ]
CMD [ "process_messages.handler" ]